# Generated by Django 3.2.23 on 2024-01-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other',
            field=models.CharField(default='', max_length=100),
        ),
    ]
