# Generated by Django 3.2.23 on 2024-01-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other',
        ),
    ]
